// Generated by CoffeeScript 1.10.0
var folderize;

folderize = require('../../common/util').folderize;

module.exports.CONFIG = {
  defaults: {
    group: 'com.fadv.integrations'
  },
  mule: {
    version: '3.7.1',
    tools: {
      version: '1.1'
    },
    artifact: {
      type: String,
      required: false,
      "default": ''
    }
  },
  options: {
    community: {
      desc: 'Creates a Mule Community Edition (CE) project',
      alias: 'ce',
      type: Boolean,
      defaults: false
    },
    enterprise: {
      desc: 'Creates a Mule Enterprise Edition (EE) project',
      alias: 'ee',
      type: Boolean,
      defaults: false
    }
  },
  questions: {
    edition: function(self) {
      return {
        when: function() {
          return (self.options.community && self.options.enterprise) || (!self.options.community && !self.options.enterprise);
        },
        type: 'list',
        name: 'edition',
        choices: ['CE - Community Edition', 'EE - Enterprise Edition'],
        "default": 0,
        message: self.options.community && self.options.enterprise ? 'Both community and enterprise switches has been provided, which one?' : 'Neither CE no EE flag was provided. which one?'
      };
    },
    group: function(self) {
      return {
        when: function() {
          return !self.group;
        },
        type: 'input',
        name: 'group',
        message: 'Enter your group id',
        "default": 'com.fadv.integrations'
      };
    },
    artifact: function(self) {
      return {
        when: function() {
          return !self.artifact;
        },
        type: 'input',
        name: 'artifact',
        message: 'Enter your artifact id',
        "default": function(answers) {
          var name;
          name = self.name || self.appname || '';
          return folderize(name);
        }
      };
    },
    version: function(self) {
      return {
        when: function() {
          return !self.version;
        },
        type: 'input',
        name: 'version',
        message: 'Enter your project version (semver)',
        "default": '1.0.0'
      };
    }
  }
};
