// Generated by CoffeeScript 1.10.0
var DOMParser, XMLSerializer, XmlUtil, fs, xpath;

fs = require('fs');

xpath = require('xpath');

DOMParser = require('xmldom').DOMParser;

XMLSerializer = require('xmldom').XMLSerializer;

XmlUtil = (function() {
  function XmlUtil() {}

  XmlUtil.LoadXmlFile = function(file) {
    var doc;
    return doc = new DOMParser().parseFromString(fs.readFileSync(file, 'utf8'), 'text/xml');
  };

  XmlUtil.LoadXmlString = function(string) {
    var doc;
    return doc = new DOMParser().parseFromString(string, 'text/xml');
  };

  XmlUtil.SerializeToString = function(doc) {
    return new XMLSerializer().serializeToString(doc);
  };

  XmlUtil.WriteXmlFile = function(file, doc) {
    return fs.writeFileSync(file, this.SerializeToString(doc));
  };

  XmlUtil.AppendXmlStringToXPath = function(doc, nxpath, xmlString) {
    return this.AppendXmlStringsToXPath(doc, nxpath, [xmlString]);
  };

  XmlUtil.AppendXmlStringsToXPath = function(doc, nxpath, xmlStrings) {
    var i, len, results, targetNode, xmlString;
    targetNode = xpath.select1(nxpath, doc);
    results = [];
    for (i = 0, len = xmlStrings.length; i < len; i++) {
      xmlString = xmlStrings[i];
      results.push(targetNode.appendChild(this.LoadXmlString(xmlString)));
    }
    return results;
  };

  XmlUtil.RemoveNodesByXPath = function(doc, nxpath) {
    var i, len, results, targetNode, targetNodes;
    targetNodes = xpath.select(nxpath, doc);
    results = [];
    for (i = 0, len = targetNodes.length; i < len; i++) {
      targetNode = targetNodes[i];
      results.push(targetNode.parentNode.removeChild(targetNode));
    }
    return results;
  };

  XmlUtil.XPathValue = function(doc, nxpath, ns) {
    var select;
    if (ns == null) {
      ns = null;
    }
    select = xpath.useNamespaces(ns);
    return select(nxpath, doc)[0].nodeValue;
  };

  XmlUtil.XPathFromFile = function(file, nxpath) {
    var doc;
    doc = this.LoadXmlFile(file);
    return xpath.select1(nxpath, doc);
  };

  return XmlUtil;

})();

module.exports = XmlUtil;
